{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "target = [#'affenpinscher',\n",
    "#'afghan_hound',\n",
    "#'african_hunting_dog',\n",
    "#'airedale',\n",
    "#'american_staffordshire_terrier',\n",
    "#'appenzeller',\n",
    "#'australian_terrier',\n",
    "#'basenji',\n",
    "#'basset',\n",
    "#'beagle',\n",
    "#'bedlington_terrier',\n",
    "#'bernese_mountain_dog',\n",
    "#'black-and-tan_coonhound',\n",
    "#'blenheim_spaniel',\n",
    "#'bloodhound',\n",
    "#'bluetick',\n",
    "#'border_collie',\n",
    "#'border_terrier',\n",
    "#'borzoi',\n",
    "#'boston_bull',\n",
    "#'bouvier_des_flandres',\n",
    "#'boxer',\n",
    "#'brabancon_griffon',\n",
    "#'briard',\n",
    "#'brittany_spaniel',\n",
    "#'bull_mastiff',\n",
    "#'cairn',\n",
    "#'cardigan',\n",
    "#'chesapeake_bay_retriever',\n",
    "#'chihuahua',\n",
    "#'chow',\n",
    "#'clumber',\n",
    "#'cocker_spaniel',\n",
    "#'collie',\n",
    "#'curly-coated_retriever',\n",
    "#'dandie_dinmont',\n",
    "#'dhole',\n",
    "#'dingo',\n",
    "#'doberman',\n",
    "#'english_foxhound',\n",
    "#'english_setter',\n",
    "#'english_springer',\n",
    "#'entlebucher',\n",
    "#'eskimo_dog',\n",
    "#'flat-coated_retriever',\n",
    "#'french_bulldog',\n",
    "#'german_shepherd',\n",
    "#'german_short-haired_pointer',\n",
    "#'giant_schnauzer',\n",
    "#'golden_retriever',\n",
    "#'gordon_setter',\n",
    "#'great_dane',\n",
    "#'great_pyrenees',\n",
    "#'greater_swiss_mountain_dog',\n",
    "#'groenendael',\n",
    "#'ibizan_hound',\n",
    "#'irish_setter',\n",
    "#'irish_terrier',\n",
    "#'irish_water_spaniel',\n",
    "#'irish_wolfhound',\n",
    "#'italian_greyhound',\n",
    "#'japanese_spaniel',\n",
    "#'keeshond',\n",
    "#'kelpie',\n",
    "#'kerry_blue_terrier',\n",
    "#'komondor',\n",
    "#'kuvasz',\n",
    "#'labrador_retriever',\n",
    "#'lakeland_terrier',\n",
    "#'leonberg',\n",
    "#'lhasa',\n",
    "#'malamute',\n",
    "#'malinois',\n",
    "#'maltese_dog',\n",
    "#'mexican_hairless',\n",
    "#'miniature_pinscher',\n",
    "#'miniature_poodle',\n",
    "#'miniature_schnauzer',\n",
    "#'newfoundland',\n",
    "#'norfolk_terrier',\n",
    "#'norwegian_elkhound',\n",
    "#'norwich_terrier',\n",
    "#'old_english_sheepdog',\n",
    "#'otterhound',\n",
    "#'papillon',\n",
    "#'pekinese',\n",
    "#'pembroke',\n",
    "#'pomeranian',\n",
    "#'pug',\n",
    "#'redbone',\n",
    "#'rhodesian_ridgeback',\n",
    "#'rottweiler',\n",
    "#'saint_bernard',\n",
    "#'saluki',\n",
    "#'samoyed',\n",
    "#'schipperke',\n",
    "#'scotch_terrier',\n",
    "#'scottish_deerhound',\n",
    "#'sealyham_terrier',\n",
    "#'shetland_sheepdog',\n",
    "#'shih-tzu',\n",
    "#'siberian_husky',\n",
    "#'silky_terrier',\n",
    "#'soft-coated_wheaten_terrier',\n",
    "#'staffordshire_bullterrier',\n",
    "#'standard_poodle',\n",
    "#'standard_schnauzer',\n",
    "#'sussex_spaniel',\n",
    "#'tibetan_mastiff',\n",
    "#'tibetan_terrier',\n",
    "#'toy_poodle',\n",
    "#'toy_terrier',\n",
    "#'vizsla',\n",
    "#'walker_hound',\n",
    "#'weimaraner',\n",
    "#'welsh_springer_spaniel',\n",
    "#'west_highland_white_terrier',\n",
    "#'whippet',\n",
    "#'wire-haired_fox_terrier',\n",
    "#'yorkshire_terrier'\n",
    "'otterhound face'\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "#pip install selenium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "#pip install apscheduler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "#크롤링이 안될때 xpath 변경 확인 https://hidden-loca.tistory.com/25"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "otterhound face crawling ready\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3178:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUVFRgVFhYYGRgaGhoZGhgYGhoYGBgaGBocGhgYGBgcIS4lHB4rHxoaJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QGhISGjQhISE0NDQxNDQxNDQ0MTQ0NDQ0NDQ0MTQ0NDE0NDQ0MT80NDQ0NDQxMTQ0NDE0NDQxMTExMf/AABEIAM8A9AMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAFAAEDBAYCBwj/xAA9EAABAwIEBAQEAwYFBQEAAAABAAIRAyEEEjFBBVFhcQYigZETobHwMsHRBxRCUuHxI4KSotIVFzNyslP/xAAYAQADAQEAAAAAAAAAAAAAAAAAAgMBBP/EACQRAAICAwEAAgICAwAAAAAAAAABAhEDEiExQVEiYRNSBDKR/9oADAMBAAIRAxEAPwD1lQ4muGNLjoplS4qwupmP7rkLr0A8N4/mrvYTAJho5rWMeCJC8n4hRyVZba822vqFt+B8XzNDXXIi/dTjJ+MrkgmrRpJSXDXyF1Kqc9CTpl1C0BkxThMUAJJIpkGjhOuU6DB06ZJBgkkk6AGKQSKQQaJKU6ZBgk0qtjMW2m3M4+m5QOtjDUeC0Fo6b9SklJR9KRg5GlSlAq2Je0QXEdeaZuMqt8w843B1WfyIb+Jh5JVMDjG1AdiNQdlchOnZNqmMkknC0w5hJdpICyJVOJA5DlMEfPorAcq+ObmaY1+qV+Dr0874wBmkrrhmJyuF9YnrGn5KXjNMtkwP810LBcGgiCJ/0+qj8nUuo9I4XjQ5obNwEVa5YXg+Lh0TF/ktfhqsqsXaOecaZeCdcMK7TEmKEiEklpgyeEydYA0J0ky0B4ShJJACSSSQAikkUkAJQ4nENY0ucYH3YKWVkPEPGGPf8EHytMudrcfollKkPCOzIajnVahc+97QbNG0dVeY9rcob2vr/VUsBUaYLdDYX25ojQYC+ZsN+S5X1nXSSLfww/UFO9l4A99FH8YtJM2HIfcqo/iIMEafd0OkYk2LEU3McHtMOJv/AC9iOSP4PEB7Z33Czb+JSIAHLmu+DY8/EDedlXHKieSFo1MJoTpK5zCSSSQAPZUSqPsqFCtZTh6CgG4xTBBi/oJWVuySdtv1sttj3CLhY3iodnOWwH3ElQlxl4Pg+DxgnMLbQe61nDMZnOunz9V5lVqOL8p05umOmiM4DFPpAZSTuLyBe9+SE6CS2PVKL1ZYUD4bjA5rTuQEWpvVUyEok6SYFOmJiSCSQKAEklKUrQEklKSAEnhKU0oAcqN7w0STZRYnFNYLrI8a8RSS1lxEf3WMaMWy34j4+GNLGG5Gv6Lz7HvLWzNyb9VLj6tiTvp6p2YMlrJuCBJ26lc8+s68aUUHsLXdSo0/LrlJJ2zGfvuiuI4hl7SPWYj6hCMcC6kyJuQB1yz+QVepjA5mUnzNAHe/lP3yU/kpVo1vDK2druTRE83ES4/fNO/BNeCzS31ug/hqv5GDY/MhuX9fZarKGgOPJMukpPUzeDo5M9IggXLSXBxnnzE8lWwVYte1w1zC3UarUuYyo2Rt8iOazWOb8J5Nomffb3J+SK1NTUjc03hwBGhC6Q3geJz0x0+huETC6Yu0cclTFCSSS0wxuFrIix8rP4OsjOGfKChZqUM4hZvjeDy3Ann/AEWsphQ8TwReyxuklG0NGVM8g4iXl5ymI2/srmExeXLJkcjsTchXOM8Oe0l7o5TuUADWA+ZxsbCSb9lL9HQvs1dDjjxYAQCLjWARPTSQtPT8W4cTmflI52J7BeXYzGikCRAnlqdrwgB4iXvzOHZUhFk5uJ9DYLjtF7C8va0NMEkwq1Xxlg2zFUOAsS0EieXVeH08Q9/lBMbiZCj/AHdzZJdEemqo6RLWz2TFftDwrJDQ9xHYAz1m3qpuHeO8NUAzE050zXHuF4fRFzqZ5an12Vh9Z4GWHZY32WNmqCPfB4jw5EioCBqRJjuNVN/1uhE/EZHf2K+d6WMe29wOv9VNiMc8Nkvyg7aa7xsjoaRPd8V4swjGyarT0BEm8amB81EfGeDDZ+KNYiCT8rL55zl34iTF5PLr1UVPFOboY122TqNiOkfS1PxHhnR/iNE6Sde0KjxDxnhmWa8PPSYHcr5+bxF8TmMjkVdwLnOMElzjE3MNtJlGoKn4bzjfjBz3eV0Ai4H1VGhXL4dInS+o9EBp8PaXaeoBP9UZwlYMGSADBuRoAPdJJ/Q8US45w2RTA4jOxsDuOw/RCKdTM4cp1RDw9SIcW6ifrb81z9OhVRoab2vZlI/AbDoAdPks7xXD5Ph1NM0td/m/DI/9gPdaNlNodcxmGX5wfpCzvH8OWsY0uJvI5QyoDPzCxo2LNL4epQxrthJUHHvGlOgHNdaLAQS4nlH3oouGY7IxoJ3I9lkvGb2VmQT5gSWneRIM9CS75JsdOSsWadNkuG/aA5jnEtJYXRq3MJ3gm/otfhmurNLnmev0B6rxLhOFa6sxr/whwJjUxeB3Xp/A/FE1yx0FpBbbobT25quaKVUTxNtOzWcDxuWoG6AiI7aLYgrz/DV2OxDGg3J+Yt+S3zNAiD4Tyrp1KSSSckeW4OpdaXAOWUwuq0vDnrSgfw6tgKnhyrjClABce4F8bzB2VwFiW5h/psvN+I8AqMe5zAXZdXutmML2ghZXxxiWsoFg/FUtb+X+IpJL5HhJ+HjWPpueL35qi6gGZZi42vE/mtZ8JjBpI+9gh1XCy9rmiADo63yWRyfBSULBGHp5HQHGOW/qrmKeXQ0i359SrWIw0EmR3UAYCfxWGvpCbZPotUQYJha4k67Abd1PVEmJd3Fp/RSYdzRa/c9BN0qz2mSDJIJEdLlHbBAssdMbAzoPclVsY/NaNN+fVE31PKQRaDr6fr80Le+do7an7n5KkScuHGUln36KoacCT2U7XmelyoKjp+qqibO6bnE5WlaLhnl8jRme65IvHOVnaDL3MI7wyo1uYMBJdqdLNvEDuUmR8Hxq2aDD4WHh2YkxBJ/JS40kfggEC5N+4Ai/uoG1Jc1oNokx12P3upOJAOO50hu3crmsvqQ8Pf5mzFz2i+i2nCsHkIg2Nyf/AGLQ36E+qweMpuaWluojTn+i2/COIse2mLSAJA5iR9UrNRW8QZ2/Cy6Zrn1MhQ+IK3+A1zozAlvcEyf/AJ1S8S4p7KJdH8QI/wBU29LeizL+J/FEbGCJ2IifoiuGkeN46fhBwPmB06EW+YKzWO4m55MTB5me6n4pQLXlouNY73hRYLhbnuE6SJV4RjFWTm5N0jjA4V78z2g5WQXEbZrD76habw/wp+drwJMes7z1Ex6L0vwXwaj8DK6m2IAiBeAAT3OUeoR3D+GqTH5xa4PtaPYIm3IWMlH0z/h7w85j21X3cTI6Tut61M1gAgLpYlROUthJJJJhDyjDC6NYJ8FCKLUQwzlpQ0+GqWV+m9AsJUROnUWAT43GBjZ1OwXnfHajnvLnGT96LW8YfIn7JWWxLeftuVz5Gy2OKAFaibD1XNOgSRmvJKJ1qRDrjXbb1TtogG9gPqpnRQIx2ELm5Q3XWOv5oPUwmQOH8U6dzBWzLQWk/fos5j2OcScu4IvrGn5p4y6TlEBPe67eeg5T9hKm4QBuGkHvF1Zx1B+eANvUQ28KtTpERaTqZ5zoVdOyL4zkuBIaDNo6SqIp89h9/Qolh8KCAdybdp1T18OIcfaepP5J06FasE1qoMEDmfSbfRU3FW8RT8x2t30H37qBzNtyVVUSZPgaOcmddhflM2Wi4RhQMz5AAbE876hA8BUDS4kTb7stHSqZfISNAST0vHZQystiRao4eIO0kx9SeyWKBhsbyfTUyrjKeZrANCATzK5rjMZjb0C5WzpUSlVqh0NOoufdUKmIcy7DudNt7K2aRDj1BCp16WQNLgYmCfaxTxEkqJ38dqkGnVIe0iQYggxYqk1+YnI2LmOxj9F3icJJMXkW7bFEeEYI5ZIt9LprRiKH/T3OMm56rS+EPDz3vBNwDMuuO0c1Ybh2xMGRyi4PTotv4VwcMDtOiaKEkw3w3Bim3KIjtCvtC5hdBOQfR0kkkCiSSSQB5cwK1QKqSp6RTFAxh3IhTchOGeiVNywCjxV0vA6IS46korxYaH0QWtUvEa2C58npfG+ED6c9Tr6T9FMymCNJ+/ooaQN82hMAdAr7GzNtLKZYqvbsIuhOOblI69NJRvEshpJ1GkKnixHmiwafVxsB8igAJjaXn/ygnkC4ZQ33uhmxJbvHcAwPXRFeIv8AhkjVxuY7SPoPZV6VLyyRsFSMqElGwMaobPN2g5c/qoar3OOm/wDdEa+EkZgN7KriaZGUTFiTzKsmmSaBWJo+YkSdZ7nX5KkTEIm50neDtvH2VWrNv6fVVjIk4nOFu4QJkgkdAtAxnnIIAP15INwtnnAO5+i0b/M+YsIE87Xv6qGd9LYVwKYAksH82kHXXb0RCqxsW9Oo+7Klh25SD/D02nRFKMNaJ8wFhzHOOq5bOqijhcO0mCJi4/uouIcOzNIbpOaPyRGjSAIc0z5XP+ZhTupOMOBvMae4WxdCyjYAweAzhgg+QxPIErVYbhoaGyLXB+o+afheHGd4izosj7GCI9iqp2SlwzWKw4Dmt669JW64XSysA2hZ12Gz1GjkZWrpNgAKkSEiaUpXGZIOToSiQFJcApZlhlEiSjzJLQo8s+IrNFyGMcr9J6cYJYd8IpQegtJyv0HrAO+Jv8qB0qUmTr96IrxOoA25VHD1BqdFz5PS+Pw4DACDE8ht07qUOIgbqQ3cCNI/NcO/FfXYdApFTirTm0qnjHhrJta/sCVJi3kHseexsSsz4rxT2tY0aOB+Vh8kyjboG6QMxPE89WeZLZ9hPyJ9UW4Y4vZfayzOFoOLwd5n3WwwrMjOqq4q6Ql16V8RSOgCH4kCc0aAwOiPG/sh+JwekfdgEauJlpmUezO5xFk1cHMLQI+yiL8MW2I1OvquKmHJvHceibcXQocPdle07CVqsO0RGpMHtyWdZhYIdvOneEXbULQJkZhlB6i6nkexTHGgwMWPKYtr0vqPdSUsZN2w4SJAOo5oW2kS2ZuQYHNFuFcNDRMmDqDrtED3C56LhSgwFpyfyuHQK5g2ZmNP+Y+jbqhRqZGFw2JPpMK7gMUItbQ+x09rLY9YsvAjhWAS7nF9iOfurbKtihVKtAy9z0AUVDHhwLR0HzgqqINWHOFkOeT7eiONchPCsJkBJ3RIFVj4Ql6Sly6DlDmTgpxSYOSzKKV1mQB3mTqLMkgDyRj1covQ8FT03pwQXpPV2nUQqi9WzVACxmog4hWk39Ama9oaPb1KqPh/P07qZkF4B/hggdVzSZ1QVIvYep5TfTWPyXbjBc+0jygfmq1Mw12mv1URqFrTPInvsEoxX4gXZSZ1Do9BP5LM8bqF+TeAT7lGsdXlhaPxaD1j+qH0MGXEGLfTkmjwVsi4Tg7ye6l4zxL4TfKAXnRp5buhEg3IEE41ww1gHMdle0EDk4cjy7q8I/ZHJJvwh4Vx4ueGVI81gdIdNgen9FpWHmvL2hzSQRJBIN9CDFiitHjdZgjObWuA6I6kSqyjZKM69N2/CMdqFWq8OgaLIjjNaf8AzOnnaOlgEb4V4tAOTEHs9osf/Zo0PZRlhKxzFsYGSARANlF4holjAAbh7XGNhpb3RZ3FsO9zGMfne8gNay5HU8gFKKbA54ffOMt+kxA9Soyi4svCSkU+FYcuglpIaR3vyRjFQywnlH3uqWFJa9kHyxPsZhXH1jUfGW0+0BRfhW+lXEVAGHXS/RRt4g1gDdyBMzp/dT8WaGscQL5TosYyo975g6wB2+5TRj8iSdmrxOLc5xazceY72m3zRDgmFuOc2QnhdExfWPVargtO4totTtiy4jVU9F2FywWXS6TkYkpSSWmDymBSSQA6SZJaB5CFMwqsCpWFMASw11Bi8Rmexg3MFdUyWtnny1Swxa4FxAm7h+Q+ihkb+C+OKqy1haPMfc/0U4ogEk9FI2vMZRAOvSxK4qPc3W23oo22WIqxgztN/ZDsXii4Acz7DT9Co8djJDgNSFWwVIlxnpC0UsYLAOe6NeZ7bou7CZAQrnD6eRvdRY+sIV4x4RlK2Aq7lBK6q1LqPMnEsxfGqbqdZ4iziXt/zG/zlUKeHe/8DHO6taSPfRHPFMZ2c8rvqNfmj/B6eWiwH+QH1Ik/VV2pE9bZicZgKlHIXtjNMb6agxuinhNjX4jK9ocCx1nAEWLTofVaHjbWOoPzwQAS3ScwHly9ZQuhw40xhKjfLVcWtcBaWmPxDmAYPNbdoKpm14bwujSOanTY12kgXg7TyVDibyH22OvdHaLUJx9KapbyEn1XJmTo6sL6NhAGgE6IjRcAAAYJ3F9NUJa8k/DAnftyRnAMMCQLTttF1zHQzjHUwQeXVAsPg4dA5n5wtXXYC2390FowHlpBgX0uT+iYVE9GhDgR2K0nCmARGu4QOm8Zm2OhPMckawLrtIEQRI6LY+iT8NCCnXIXS6jlFKYpkkAKU8rlOgB5TJJLTDxzMpqZVVpVimtowv1ngstayk4O0Nb5r7xyVQHZWKNQs80eXSP6LnzcOnD0MVKYZDm6E/I/3VHxBiMtO2/vbZWaeJztkGYGhQTxLV8jRFpuUsVcbGk2pUDsPmd5pv8Ay9Ci2Cc0X+5QZmKDIECZveP4bK1SxYImdbRyRHjNl1BOtxMz2VOvjS5UqhI13UJqLpTOb5LJegXE8dXFRzW5msFpaNeZnuiJrQh2K8Rua5zWtzAbkkHa6y5J/irGUYtXJ0CqrnOcSc5J1Jbf6qVz3n8Tq59DHpLlZPiZ8TkHeSmPiZ9vK0+p/RPeT+q/6Zri+yg6m8mMr4vqN+cc0+SpIgOtoZMiOquHxM/+Qe/9F2PEz/5B7/0ReX+qN1w/bNB4GxFf4jmPc4sLbZiTDptBOkiVq+KYFzjmYLkAGO8LCcG8QOfVYwtyy5ujj/MOi9fpMESpyUpWpKhvxjTi7RhsJQe199jeeQRKlXgkt0gAqpxeq1jnAOzEkny7HWCoKGKOUE20Ec4i64pLVnXF2jQfFOSw/NDH1ROYAm8HcDurODrgtIQrGYoMMBupM+vNMnwVqmF8MBOnry3Mo5gHQR3CyuCqjIIdeZI212Wq4QPUETK2HZE8ngdancVHmTSus5SSUy5lKUGDynlcpIA6zJlzCdBpg38KcL5PoovgBpu2PRbdmDcVI/hAdqFtgYRxggBgINtNO6pPqNBgxLiRcw2OQlbzEeFw/R7mdgCg+P8AAD6pE4mByNOfnn/JSnFyZWE1FAinRLHNJIykxOi64twZ1dgDcvMa/ktDR8KPAyuewtAytGUugDQ3OqLYDhXwxBOc8yAPkiENTZyUunlzfCmLk5mNdaJB19CusL4VxYH/AIR0Gdv1XrRBH8KifWjZPqhNmYrC+G6mQZ2MzReLgepC7d4XP8g9gtZ+8dEjXtotXBWYqv4YAY4wPwuOnILyHGNh7gdj+QX0PxXHU2Un5i0Sx4EkCTlNhzK+d8QczydLp4Ppkv8AU5D27t+ZSAESR6z15JGoD/KLDbkY991yQMsSJ7XPqrEjt9LLctttfrBUIc3kdBvvuVI0ib5dtp+/6pw8AEQ0zvuLRb690AEfDTx+8U4H8Tf/ALavdat2kLwjw04NxDHG4Ba72c0r2IcfpnUexUcj6WivxRleIMayo/MZG2wE9FPTL/hjcXgcvzU/HKlN3nbeQAbXAGyt8PqMDRA0FouB3XDOKs7IS/Eg4cxzomAN+ndUePYYtcBeHcoBPL0/RXXYsOLsjIInMfS+ii4owuZndsNSTFhYJYvlDSXbIsGzKRAkadlseCvy+U+nTmsThHZ8okNcIIy2i2pHutFgm1GPaHOkcwI2WpuLsWa2VGwCcBC8NjgH5XyJgAnQko4zDrqjLZHHKOrIQ1dBkqyzChSiiAmFKjWLv4ZVtrAuwxajLKH7uUleyJLLMsfKmyqaE2VPqzNiMsXORTZUxas1YbEWVckKfKmyI1kbsVixRPoyrxppfC6o1kbsgLVwrvsKs6mRr+i0XwVy7Dgo1kGyPE/2iYh7qjWAfgBNrxIGq89q4VxJIBuev6L6NxnguhVqOe5z5dEwWgWEQPKq7v2f4b+ar/qb/wAULdeIpeNqmz54OCeNvkf0XDsK/kfYr6FP7PKP/wCtTp+D/io3fs7o3/xqv+z/AIoU8n0ZWL7Pn392fy+q6/c3nZe/f9taB1rVJ6Bg7fwrkfsyoC/xqv8As/4rd8n0FYvs8O4bQcx4JB5fML1XgGAZWYczZcLTMdpRz/tnRv8A41X/AG/oivA/B9PClxa97i6JzRFp0AHVK1Ju2h3OCjSZk8f4Se8Qxw6B0/UJsF4ZxVJhENfyAIF4sJJXpbMIApPgJXib+BVmo8r4dwrGB9QPoZWmMpBaQee/3Kv4bh+KbVy/BLqMN1yi5NxrsvQ/3dP+79ln8P6NeYB0vD9Aw51FgdzAg+4Vo8GoHVjTprO2l5RQUk4ppljf0I8j+we3htIADI22lpiNFbAUuRLIm0f0LtfpESug5d/DSyI1ZmyGDVXq4xrbE36XVrKh1fgjXOzBz2kmTlcIPo4FTyrJX4LpsXG+nX/U2dfZJV38AaTPxavuz/gmXNr/AJX6KXi/Z//Z\" data-deferred=\"1\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"233\" height=\"198\" alt=\"Otterhound Dog Breed Information and Pictures\" data-iml=\"607.6999999284744\" data-atf=\"false\"> is not clickable at point (136, 635). Other element would receive the click: <div jsname=\"r5xl4\" class=\"islrc\" style=\"width: 551px;\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3181:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3195:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3200:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3204:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img data-ils=\"4\" jsaction=\"rcuQ6b:trigger.M8vzZb;\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"234\" height=\"215\" alt=\"Personalised Otterhound Face Masks | Yappy.com\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjWtFkcV8zv3q5CDI7TjzCnZXqB0BlAK2uDw&amp;usqp=CAU\"> is not clickable at point (138, 634). Other element would receive the click: <div jsname=\"r5xl4\" class=\"islrc\" style=\"width: 551px;\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3210:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3222:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3226:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3231:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3232:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3260:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable\n",
      "\n",
      "Exception in thread Thread-3261:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 30, in findI\n",
      "    imgUrl = driver.find_element_by_xpath('/html/body/div[2]/c-wiz/div[3]/div[2]/div[3]/div/div/div[3]/div[2]/c-wiz/div/div/div[1]/div/div/a/img').get_attribute(\"src\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 394, in find_element_by_xpath\n",
      "    return self.find_element(by=By.XPATH, value=xpath)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n",
      "    'value': value})['value']\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div[2]/c-wiz/div[3]/div[2]/div[3]/div/div/div[3]/div[2]/c-wiz/div/div/div[1]/div/div/a/img\"}\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3263:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3266:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPoq1tnncFYUB8TiDCkRaOkHrH2tallvqK_Q&amp;usqp=CAU\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"74\" height=\"240\" alt=\"Amazon.com: Healthy Breeds Otterhound Bright Whitening Shampoo 12 oz\" data-iml=\"3025.2999999523163\"> is not clickable at point (124, 628). Other element would receive the click: <div jsname=\"r5xl4\" class=\"islrc\" style=\"width: 551px;\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3270:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3271:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3274:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxZe_OKoKzdXQR_FyfIrODCsUup-uPRqh7zQ&amp;usqp=CAU\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"202\" height=\"202\" alt=\"courtenaytracyhounds Instagram posts (photos and videos) - Picuki.com\" data-iml=\"3061.1999999284744\"> is not clickable at point (135, 633). Other element would receive the click: <div jsname=\"r5xl4\" class=\"islrc\" style=\"width: 551px;\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3277:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3280:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3286:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img data-ils=\"4\" jsaction=\"rcuQ6b:trigger.M8vzZb;\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"225\" height=\"225\" alt=\"Pet Otter Face Masks | Redbubble\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgTciRaggQSFyXvwtpqQ-BkzXmNAYXnXakyg&amp;usqp=CAU\"> is not clickable at point (141, 629). Other element would receive the click: <div jsname=\"r5xl4\" class=\"islrc\" style=\"width: 551px;\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3294:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (168, 657)\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3302:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3305:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3307:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3308:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img data-ils=\"4\" jsaction=\"rcuQ6b:trigger.M8vzZb;\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"257\" height=\"196\" alt=\"A Snippet of Otterhound History\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9m09h7vnmJYzGL5K77kwDz7_EuIWirD8geA&amp;usqp=CAU\"> is not clickable at point (169, 625). Other element would receive the click: <div jsname=\"r5xl4\" class=\"islrc\" style=\"width: 551px;\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3313:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3314:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3316:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3328:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3340:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3348:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3357:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img data-ils=\"4\" jsaction=\"rcuQ6b:trigger.M8vzZb;\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"227\" height=\"223\" alt=\"Gracie - Rocky Mountain Labradoodles - Australian Labradoodles\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5-0zspxmCAHWB4hqeEwLd63pEl4GGwJZWkg&amp;usqp=CAU\"> is not clickable at point (149, 627). Other element would receive the click: <div jsname=\"r5xl4\" class=\"islrc\" style=\"width: 551px;\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3363:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3365:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3378:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3395:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3409:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3417:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 641, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 569, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 649, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 403: Forbidden\n",
      "\n",
      "Exception in thread Thread-3421:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img data-ils=\"4\" jsaction=\"rcuQ6b:trigger.M8vzZb;\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"183\" height=\"276\" alt=\"25 of the Rarest Dog Breeds\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0gkuhHOSUiVcdjj7wBMlMGJ7_z7B0NuoJTw&amp;usqp=CAU\"> is not clickable at point (130, 619). Other element would receive the click: <div data-ved=\"0CHkQMyiBAmoXChMIiKrFuOym8QIVAAAAAB0AAAAAEAM\" jsaction=\"IE7JUb:e5gl8b;dtRDof:s370ud;v03O1c:cJhY7b;\" data-ictx=\"1\" data-id=\"LwxpxOKTICiFcM\" jsname=\"N9Xkfe\" data-ri=\"257\" class=\"isv-r PNCib MSM1fd BUooTd\" jscontroller=\"H9MIue\" jsmodel=\"lbVNPd Whqy4b\" jsdata=\"j0Opre;LwxpxOKTICiFcM;$157\" style=\"width: 177px; height: 189px;\" data-tbnid=\"LwxpxOKTICiFcM\" data-ct=\"6\" data-cb=\"9\" data-cl=\"12\" data-cr=\"0\" data-tw=\"275\" data-ow=\"750\" data-oh=\"500\" data-os=\"2\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n",
      "Exception in thread Thread-3425:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 27, in findI\n",
      "    image.click()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n",
      "    self._execute(Command.CLICK_ELEMENT)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n",
      "    return self._parent.execute(command, params)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <img data-ils=\"4\" jsaction=\"rcuQ6b:trigger.M8vzZb;\" class=\"rg_i Q4LuWd\" jsname=\"Q4LuWd\" width=\"183\" height=\"276\" alt=\"Otterhound Images, Royalty-free Stock Otterhound Photos &amp; Pictures |  Depositphotos\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz9qIr0jWBoaFqKNyTJzO5EPbN0zfuCDLxuw&amp;usqp=CAU\"> is not clickable at point (124, 610). Other element would receive the click: <div class=\"fxgdke\">...</div>\n",
      "  (Session info: chrome=91.0.4472.106)\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "otterhound face------------------ complete\n",
      "CRAWLING COMPLETE\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3424:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-10-bc12107eba29>\", line 31, in findI\n",
      "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 247, in urlretrieve\n",
      "    with contextlib.closing(urlopen(url, data)) as fp:\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 525, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 543, in _open\n",
      "    '_open', req)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 503, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 1393, in https_open\n",
      "    context=self._context, check_hostname=self._check_hostname)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\urllib\\request.py\", line 1353, in do_open\n",
      "    r = h.getresponse()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\http\\client.py\", line 1369, in getresponse\n",
      "    response.begin()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\http\\client.py\", line 310, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\http\\client.py\", line 271, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\socket.py\", line 589, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\ssl.py\", line 1071, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"C:\\Users\\BVer\\miniconda3\\envs\\crawl\\lib\\ssl.py\", line 929, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#name = 'iu' #검색어\n",
    "how_many = 200 #가져올 사진 수\n",
    "path = 'C:\\\\Users\\\\BVer\\\\image_crawler\\\\' #해당 코드 파일 위치 \n",
    "\n",
    "from selenium import webdriver\n",
    "from urllib.request import urlopen\n",
    "#from bs4 import BeautifulSoup as bs\n",
    "from urllib.parse import quote_plus\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "import urllib.request\n",
    "import time\n",
    "import os\n",
    "import shutil\n",
    "\n",
    "import threading\n",
    "import time\n",
    "from apscheduler.schedulers.background import BackgroundScheduler\n",
    " \n",
    "\n",
    "def start_findI():\n",
    "    t = threading.Thread(target=findI)\n",
    "    t.start()\n",
    "    return t\n",
    "\n",
    "def findI():\n",
    "    findI = threading.currentThread()\n",
    "    image.click()\n",
    "    time.sleep(1.7)\n",
    "    #imgUrl = driver.find_element_by_xpath('/html/body/div[2]/c-wiz/div[3]/div[2]/div[3]/div/div/div[3]/div[2]/c-wiz/div/div[1]/div[1]/div/div[2]/a/img').get_attribute(\"src\")\n",
    "    imgUrl = driver.find_element_by_xpath('/html/body/div[2]/c-wiz/div[3]/div[2]/div[3]/div/div/div[3]/div[2]/c-wiz/div/div/div[1]/div/div/a/img').get_attribute(\"src\")\n",
    "    urllib.request.urlretrieve(imgUrl, name + str(count) + \".jpg\")\n",
    "    #print(name + str(count) + \".jpg --- find\")\n",
    "\n",
    "sched = BackgroundScheduler()\n",
    "sched.start()\n",
    "for name in target:\n",
    "    driver = webdriver.Chrome(path + 'chromedriver.exe')\n",
    "    driver.get(\"https://www.google.co.kr/imghp?hl=ko&ogbl\")\n",
    "    elem = driver.find_element_by_name(\"q\")\n",
    "    elem.send_keys(name)\n",
    "    elem.send_keys(Keys.RETURN)\n",
    " \n",
    "    SCROLL_PAUSE_TIME = 1\n",
    " \n",
    "    last_height = driver.execute_script(\"return document.body.scrollHeight\")\n",
    " \n",
    "    while True: #페이지 로딩\n",
    "        driver.execute_script(\"window.scrollTo(0, document.body.scrollHeight);\")\n",
    "        time.sleep(SCROLL_PAUSE_TIME)\n",
    "        new_height = driver.execute_script(\"return document.body.scrollHeight\")\n",
    "        if new_height == last_height:\n",
    "            try:\n",
    "                driver.find_element_by_css_selector(\".mye4qd\").click()\n",
    "            except:\n",
    "                break\n",
    "        last_height = new_height\n",
    " \n",
    "    images = driver.find_elements_by_css_selector(\".rg_i.Q4LuWd\")\n",
    "    print(name + ' crawling ready')\n",
    "    \n",
    "    try: #name 폴더 만들기\n",
    "        os.makedirs(path + '\\\\' + name)\n",
    "    except:\n",
    "        pass\n",
    "    \n",
    "\n",
    "    count = 1\n",
    "    trycount = 0\n",
    "    for image in images: #로딩된 페이지에서 크롤링\n",
    "        if(sched.running): #스레드가 작동중이지 않으면 멈춤\n",
    "            trycount += 1\n",
    "            try:\n",
    "                t = start_findI()\n",
    "            except:\n",
    "                if(trycount > how_many*3):\n",
    "                    print(name + ' crawling ERROR')\n",
    "                    break\n",
    "                else:\n",
    "                    pass\n",
    "            finally:\n",
    "                time.sleep(3)\n",
    "                try:     \n",
    "                    t.do_run = False             \n",
    "                except:\n",
    "                    pass\n",
    "                finally:\n",
    "                    try:\n",
    "                        if(os.path.isfile('{0}{1}.jpg'.format(path, name + str(count)))): #파일 저장 확인 후 이동 시키고 카운트업\n",
    "                            from_ = '{0}{1}.jpg'.format(path, name + str(count))\n",
    "                            to_ = '{0}{1}\\{2}.jpg'.format(path, name, name + '_0' + str(count))\n",
    "                            shutil.move(from_, to_)\n",
    "                            count += 1\n",
    "                    except:\n",
    "                        pass\n",
    "                    finally:\n",
    "                        if(count > how_many):\n",
    "                            break     \n",
    "        else:\n",
    "            break\n",
    "    try:\n",
    "        driver.close()\n",
    "    except:\n",
    "        pass\n",
    "    finally:\n",
    "        print(name + '------------------ complete')\n",
    "        \n",
    "print('CRAWLING COMPLETE')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
